---
abstract: 'from DBI tables does generate routes, make authentication and make restrict access (authorization) to requests. Plugin makes an auth operations throught the plugin L<Mojolicious::Plugin::Authentication> and OAuth2 by L<Mojolicious::Plugin::OAuth2>.'
author:
  - 'Mikhail Che <mche@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-RoutesAuthDBI
no_index:
  directory:
    - t
    - inc
requires:
  DBI: '1.6'
  DBIx::POS::Template: '0.01'
  Hash::Merge: '0.2'
  Mojolicious: '6'
  Mojolicious::Plugin::Authentication: '1.29'
  perl: '5.014'
version: '0.777'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
